[project]
name = "fasthtml-template"
version = "0.1.0"
description = "A \"Hello World\" template for FastHTML"
authors = [
    {name = "Bob Ambrose", email = "bambrose24@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-fasthtml>=0.12.15",
]

[tool.poetry.dependencies]
python = "^3.13"
python-fasthtml = "^0.12.15"

